import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const kPrimaryColor = Color(0xFF00BF6D);
  static const kSecondaryColor = Color(0xFFFE9901);
  static const Color scaffoldTopGradientClr = Color(0xff8D8AD3);
  static const Color scaffoldBottomGradientClr = Color(0xff454362);
  static const Color overlayContainerClr = Color(0xff2E2E2E);
  static const kContentColorLightTheme = Color(0xFF1D1D35);
  static const kContentColorDarkTheme = Color(0xFFF5FCF9);
  static const warningColor = Color(0xFFF3BB1C);
  static const kErrorColor = Color(0xFFF03738);
  static const Color primary = Color(0xff1d3a69);

  static const Color primaryB = Color(0xff04183b);
  static const Color primary_80 = Color(0xCC311629);
  static const Color white = Color(0xffffffff);
  static const Color blueBright = Color(0xff0096FF);
  static const Color titleTextColor = Color(0xff1d2635);
  static const Color orange = Color(0xffE65829);
  static const Color grey = Color(0xff747F8F);
  static const Color kBlack = Color(0xFF2D3243);
  static const Color kBlackHalf = Color(0xFF454533);
  static const Color redShade4 = Color(0xFFFF4758);
  static const Color redShade5 = Color(0xFFFB4656);
  static const Color facebookBlue = Color(0xFF44619D);
  static const Color lighterBlue = Color(0xFFD8F4FD);
  static const Color violetShade200 = Color(0xFF655796);
  static const bbPrimaryColor = Color(0xFF29abe2);
  static const bbSecondaryColor = Color(0xFFfcee21);
  static const bbPrimaryTextColor = Color(0xFF2E3192);
  static const bbGreenTextColor = Color(0xFF00AD8F);
  static const bbLightRedColor = Color(0xFFEF8E91);
  static const bbShadowColor = Color(0X95E9EBF0);
  static const bbViewColor = Color(0xFFDADADA);
  static const bbTextSecondaryColor = Color(0xFF000000);
  static const bbLightBlueColor = Color(0xFF9BA1FF);
  static const bbOrangeColor = Color(0xFFFF7648);
  static const bbFacebook = Color(0xFF3B5997);
  static const bbYellowColor = Color(0xFFFEBA39);
  static const bbAppColor1 = Color(0xFF2E3192);
  static const bbAccentColor = Color(0xFFFF4891);
  static const bbPurpleColor = Color(0xFFB226B2);
  static const bbTealColor = Color(0xFF4DC591);
  static const bbIconSecondaryColor = Color(0xFF9E9E9E);
  static const bbScaffoldColorDark = Color(0xFF121212);
  static const bbTextSecondaryLightColor = Color(0xFF757575);
  static const bbSplashSecondaryColor = Color(0xFFD7DBDD);
  static const Color fColor = Color(0xff201F2F);
  static Color shimmerBasColor = const Color(0xCC311629);
  static const Color green = Color(0xff008000);
  static const Color violet = Color(0xFF8764C3);
  static const Color athensGray = Color(0xFFEDEEF2);
  static const Color codGray = Color(0xFF1A1A1A);
  static const Color black = Color(0xff20262C);
  static const Color blackPure = Color(0xff000000);
  static const Color blue = Color(0xFF4045EE);
}
